### ISSUE TITLE
Error on Build (113 & 116)

### ISSUE THREAD

**Issue by monkeyworknet** [mapcrafter/mapcrafter#370]
Error:   https://pastebin.com/uA1KpHTL

Get same error if I try and build 116 or 113.
Never had an issue in the past doing the build

**Comment by monkeyworknet** [comment]
Fixed first issue by adding 

SET(CMAKE_CXX_FLAGS "-std=c++11 -O3") 

To top of CMakeLists.txt

Now getting this issue when building:

https://pastebin.com/UnUcXXbm

[ 80%] Building CXX object CMakeFiles/mapcrafter.dir/mapcrafter.o

**Comment by beulette** [comment]
Same error for me. Something wrong in c++ but I never used it so I find no clue on how to resolve it...

**Comment by deelight2k** [comment]
Same for me ....

**Comment by fredkilbourn** [comment]
Not sure if this is the solve or not for you but on my older system I have to add `add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)` immediately after `add_definitions(-Wall)` in `CMakeLists.txt`.  Let me know if that helps?  I'm definitely not an expert either.

Make sure to `make clean` to reset the build between changing options.

**Comment by beulette** [comment]
I don't have a add_definitions(-Wall) line. So I put both lines after the add_subdirectory lines, but the build still fails, no improvement :-(

> cmake_minimum_required(VERSION 3.5)
> SET(CMAKE_CXX_FLAGS "-std=c++11 -O3")
> add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/mapcraftercore")
> add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/test")
> add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/tools")
> add_definitions(-Wall)
> add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)

**Comment by fredkilbourn** [comment]
It's right here: https://github.com/mapcrafter/mapcrafter/blob/master/CMakeLists.txt#L33

And here: https://github.com/mapcrafter/mapcrafter/blob/world113/CMakeLists.txt#L33

**Comment by beulette** [comment]
Oh ok it was in mapcrafter/ folder, not in mapcrafter/src/.
The issue we encountered was with mapcrafter/src/CMakeLists.txt.

I tryed to "make" that folder, but it failed at 91% after a lot of errors like :

> /home/mapcrafter/src/mapcraftercore/renderer/rendermodes/lighting.cpp:107:6: warning: ‘bool mapcrafter::renderer::{anonymous}::isSpecialTransparent(uint16_t)’ defined but not used [-Wunused-function]
>  bool isSpecialTransparent(uint16_t id) {

After that I re-tryed in src/ with a make clean before (who knows ^^) but still the same.

**Comment by elamperti** [comment]
@beulette  That particular line you quoted is just a warning. It may be useful to see the whole log (you can share it in a pastebin).

@monkeyworknet, @fredkilbourn, @deelight2k Could you share some details to try to pinpoint the issue?
- Are you compiling mapcrafter or building the dockerfile? (if you don't know, you are most certainly compiling)
- Operating system?
- versions of boost, libpng and cmake packages you are using?
- Architecture? (x86, x64, arm, etc)

Thanks in advance for your collaboration! I'll be trying to compile as well and see how it goes.

**Comment by beulette** [comment]
building I think, I just followed the instructions like I did for previews versions, then here I had to go to /mapcrafter/src/ and do "cmake ." and then "make".

Here are the different answers to your questions :

OS : Ubuntu 16.04.6 LTS (Xenial Xerus)
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
libpng12-dev version 1.2.54-1ubuntu1.1
libboost-iostreams-dev 1.58.0.1ubuntu1
libboost-system-dev 1.58.0.1ubuntu1
libboost-filesystem-dev 1.58.0.1ubuntu1
libboost-program-options-dev 1.58.0.1ubuntu1
build-essential 12.1ubuntu2
cmake 3.5.1-1ubuntu3

Thanks a lot :-)

**Comment by monkeyworknet** [comment]
@elamperti 

1.  Build from Source
2.  Centos 7
3.  https://pastebin.com/S59f3A72 - I've basically installed every package from boost I could think of trying to find what was wrong:
4.  Linux mc5 3.10.0-693.11.6.el7.x86_64

**Comment by monkeyworknet** [comment]
ok you can ignore my issue i'm a complete dummy so sorry for wasting time.   I was building off of:

https://github.com/miclav/mapcrafter.git

rather than:

http://github.com/mapcrafter/mapcrafter.git

@beulette  double check what repo your cloning.


Compiled without issue after you know actually pointing it to the proper repo.

Testing the actual install later this evening.

**Comment by beulette** [comment]
I was on the good repository, and I checkout-ed world116 on this.
Tried with a new install from scratch, with the good repository url and world113 last version, I still have the same issue.

**Comment by beulette** [comment]
Ok, actually I stopped following the step-by-step install, and just tried a "make install" in the src/ folder. And it worked.
Is that a problem if I didn't make the build to 100% ?
Map address (just in case, and because it's always cool to share game stuff too) : http://maitrebeulette.fr/map

Error while generating the map : 
> 2020-07-04 11:46:01 [WARNING] [default] Unknown biome with id 51
> same with id /66/67/68/72/75/78/82/88/89/92/100/104/105/106/125/152/173/177/182/199/200/203/204/207/208/209/243/...

**Comment by deelight2k** [comment]
Is this Problem fixed already?

**Comment by cliffmeyers** [comment]
I was receiving a lot of "unknown biome with id x" errors myself but I pulled latest from the `world113` branch (12ce56d65222fb9ed9de3b4fa9eb593e49a6bc88 from 09 Aug), did a `make clean` and `make` and when running I no longer receive those errors.

I still have a problem with large swaths of the map being rendered as empty white JPG but I will probably file that as a separate issue.

**Comment by elamperti** [comment]
Today I've tested building world113 from scratch and everything worked as expected. If this is still happenning for any of you after following the suggestions above please let us know.
